ListNews:
  css: "div ul.list_shnews-mid li"
  multiple: true
  type: Text
  children:
    NewsId:
      css: "li.item"
      type: Attribute
      attribute: data-newsid
    Title:
      css: "li.item div h3"
      type: Text
    Url:
      css: li.item
      type: Link
    AvatarCustom:
      css: i
      type: Attribute
      attribute: style
      format: AvatarUrl
    Sapo:
      css: p.shnews_sapo
      type: Text
    LastModifiedDate:
      css: div.time
      type: Attribute
      attribute: title
ListNews2:
  css: "div.hotnews ul.list-hotnews li"
  type: Text
  multiple: true
  children:
    NewsId:
      css: "li.hotnews-item"
      type: Attribute
      attribute: data-newsid
    Title:
      css: "li.hotnews-item div h3"
      type: Text
    Url:
      css: li.hotnews-item
      type: Link
    AvatarCustom:
      css: img
      type: Attribute
      attribute: src
    Sapo:
      css: p.shnews_sapo
      type: Text
    LastModifiedDate:
      css: div.time
      type: Attribute
      attribute: title
